version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
      - "8091:8080"
    volumes:
      - type: bind
        source: /home/ubuntu/lab12_2_xls/
        target: /data
  frontend:
    image: popbobkok5019/lab12_2:latest
    ports:
      - "8092:80"